package jp.co.kr.persistence;

import java.util.List;
import jp.co.kr.persistence.Company;
import jp.co.kr.persistence.CompanyExample;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    Company selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPANY
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    int updateByPrimaryKey(Company record);
}