package jp.co.kr.persistence;

import java.math.BigDecimal;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.COMPANY_ID
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.NAME
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ADDRESS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.ORG_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.CAPITAL
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private BigDecimal capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.BIZ_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private BigDecimal bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.EMP_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private Integer empCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.BRANCH_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private Integer branchCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.STATUS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private Integer landFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMPANY.HEAD_LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    private String headLandFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.COMPANY_ID
     *
     * @return the value of COMPANY.COMPANY_ID
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.COMPANY_ID
     *
     * @param companyId the value for COMPANY.COMPANY_ID
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.NAME
     *
     * @return the value of COMPANY.NAME
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.NAME
     *
     * @param name the value for COMPANY.NAME
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ADDRESS
     *
     * @return the value of COMPANY.ADDRESS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ADDRESS
     *
     * @param address the value for COMPANY.ADDRESS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.ORG_TYPE
     *
     * @return the value of COMPANY.ORG_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.ORG_TYPE
     *
     * @param orgType the value for COMPANY.ORG_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.CAPITAL
     *
     * @return the value of COMPANY.CAPITAL
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public BigDecimal getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.CAPITAL
     *
     * @param capital the value for COMPANY.CAPITAL
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setCapital(BigDecimal capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.BIZ_TYPE
     *
     * @return the value of COMPANY.BIZ_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public BigDecimal getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.BIZ_TYPE
     *
     * @param bizType the value for COMPANY.BIZ_TYPE
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setBizType(BigDecimal bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.EMP_COUNT
     *
     * @return the value of COMPANY.EMP_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public Integer getEmpCount() {
        return empCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.EMP_COUNT
     *
     * @param empCount the value for COMPANY.EMP_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setEmpCount(Integer empCount) {
        this.empCount = empCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.BRANCH_COUNT
     *
     * @return the value of COMPANY.BRANCH_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public Integer getBranchCount() {
        return branchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.BRANCH_COUNT
     *
     * @param branchCount the value for COMPANY.BRANCH_COUNT
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setBranchCount(Integer branchCount) {
        this.branchCount = branchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.STATUS
     *
     * @return the value of COMPANY.STATUS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.STATUS
     *
     * @param status the value for COMPANY.STATUS
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.LAND_FLG
     *
     * @return the value of COMPANY.LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public Integer getLandFlg() {
        return landFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.LAND_FLG
     *
     * @param landFlg the value for COMPANY.LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setLandFlg(Integer landFlg) {
        this.landFlg = landFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMPANY.HEAD_LAND_FLG
     *
     * @return the value of COMPANY.HEAD_LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public String getHeadLandFlg() {
        return headLandFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMPANY.HEAD_LAND_FLG
     *
     * @param headLandFlg the value for COMPANY.HEAD_LAND_FLG
     *
     * @mbggenerated Sat Oct 25 20:29:13 JST 2014
     */
    public void setHeadLandFlg(String headLandFlg) {
        this.headLandFlg = headLandFlg;
    }
}