package jp.co.kr.persistence;

public class Person {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.ID
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.NAME
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.ID
	 * @return  the value of PERSON.ID
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.ID
	 * @param id  the value for PERSON.ID
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.NAME
	 * @return  the value of PERSON.NAME
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.NAME
	 * @param name  the value for PERSON.NAME
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}
}