package jp.co.kr.persistence;

import java.util.List;
import jp.co.kr.persistence.Person;
import jp.co.kr.persistence.PersonExample;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int countByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int deleteByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	List<Person> selectByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int updateByExampleSelective(@Param("record") Person record,
			@Param("example") PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbggenerated  Sat Oct 25 20:29:13 JST 2014
	 */
	int updateByExample(@Param("record") Person record,
			@Param("example") PersonExample example);
}