CREATE TABLE COMPANY (
COMPANY_ID INT AUTO_INCREMENT COMMENT '法人ID',
NAME VARCHAR(50) COMMENT '法人の名称',
ADDRESS VARCHAR(50) COMMENT '法人の本所・本社・本店の所在地 ',
ORG_TYPE VARCHAR(50) COMMENT ' 組織形態 ',
CAPITAL DECIMAL(19,4) COMMENT ' 資本金、出資金又は基金の額 ',
BIZ_TYPE DECIMAL(19,4) COMMENT ' 業種 ',
EMP_COUNT INT COMMENT ' 常用雇用者数 ',
BRANCH_COUNT INT COMMENT ' 支所・支社・支店の数 ',
STATUS VARCHAR(50) COMMENT ' 土地の所有状況について ',
LAND_FLG INT COMMENT ' 所有する土地の有無 ',
HEAD_LAND_FLG VARCHAR(50) COMMENT ' うち本所・本社・本店の敷地の所有状況 ',
PRIMARY KEY (`COMPANY_ID`)
);

CREATE TABLE COMPANY_LAND(
COMPANY_ID INT ,
ADDRESS VARCHAR(50) COMMENT ' 所在地 ',
TYPE VARCHAR(50) COMMENT ' 土地の所有形態 ',
MESEKI INT COMMENT ' 土地の所有面積 ',
JIKI INT COMMENT ' 土地の取得時期 ',
KASHITUKE_UMU INT COMMENT ' 土地の貸付の有無 ',
RIYOU INT COMMENT ' 土地の利用現況 ',
TANAOROSHI_FLG INT COMMENT ' 棚卸資産か否か ',
SHINTAKU_FLG INT COMMENT ' 信託受益権か否か ',
PRIMARY KEY (`COMPANY_ID`)
);